# Generated by Django 5.0.6 on 2024-07-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('project_language', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
